CREATE TABLE PERSONA(
	id   int NOT NULL AUTO_INCREMENT,
	dni  VARCHAR(30),
	paterno VARCHAR(30),
	materno VARCHAR(30),
	PRIMARY KEY (id)

);



INSERT INTO PERSONA (dni,paterno,materno) VALUES ('40119572','ZEBALLOS','QUINA');
INSERT INTO PERSONA (dni,paterno,materno) VALUES ('40118515','PEREZ','JUARES');
INSERT INTO PERSONA (dni,paterno,materno) VALUES ('40187545','VERON','QUISPE');

INSERT INTO PERSONA (dni,paterno,materno) VALUES ('45128956','MESSI','DUELOS');
INSERT INTO PERSONA (dni,paterno,materno) VALUES ('52893674','GUERRERO','NIEVES');
INSERT INTO PERSONA (dni,paterno,materno) VALUES ('84516295','SUAREZ','GILO');

INSERT INTO PERSONA (dni,paterno,materno) VALUES ('97641352','LOA','LOA');
INSERT INTO PERSONA (dni,paterno,materno) VALUES ('74515289','QUISPE','YANQUI');
INSERT INTO PERSONA (dni,paterno,materno) VALUES ('62125315','GAMARRA','PALOS');



